### ISSUE TITLE
Convention & Code style

### ISSUE THREAD

**Issue by haritianaadriano** [SentimentDetector/backend-sentinent#7]
When you name your variable or when you tell your code to another developer or when your co-worker read your code, it's important to have a code readable.

**Comment by haritianaadriano** [comment]
choose the language you want to use for both variable names and error messages, in front side you can just handle corresponding with the error provided
![Capture d'écran 2024-02-07 231044](https://github.com/SentimentDetector/backend-sentinent/assets/103512767/1f67f3b8-7c83-4270-96f6-4bc059cc9a7d)

**Comment by haritianaadriano** [comment]
according with ES6, you can use export to export function and import it from another. [ES6: import, export module](https://www.digitalocean.com/community/tutorials/js-modules-es6) 
![Capture d'écran 2024-02-07 233553](https://github.com/SentimentDetector/backend-sentinent/assets/103512767/1ef70200-7a7b-4e17-8724-f31e0a6b9ce1)

**Comment by ReichmannGaly** [comment]
fixed
